#!/usr/bin/env bash
set -euo pipefail

# Flow installer
# Usage:
#   ./install.sh              — install into current directory
#   ./install.sh /path/repo   — install into target directory

TARGET="${1:-.}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

detect_version() {
  if [ -f "$SCRIPT_DIR/SPECS/VERSION" ]; then
    tr -d '[:space:]' < "$SCRIPT_DIR/SPECS/VERSION"
    return
  fi

  if [ -f "$SCRIPT_DIR/SPECS/COMMANDS/FLOW.md" ]; then
    awk '/^\*\*Version:\*\*/ {print $2; exit}' "$SCRIPT_DIR/SPECS/COMMANDS/FLOW.md"
    return
  fi

  echo "0.0.0"
}

write_default_workplan() {
  cat > "$1" <<'EOF'
# Project Workplan

Replace this file with your own tasks. Generated by install.sh fallback template.
EOF
}

write_default_archive_index() {
  cat > "$1" <<'EOF'
# Tasks Archive

**Last Updated:** YYYY-MM-DD

## Archived Tasks

| Task ID | Folder | Archived | Verdict |
|---------|--------|----------|---------|

## Historical Artifacts

| Folder | Description |
|--------|-------------|
| [_Historical/](_Historical/) | Non-task artifacts |

## Archive Log

| Date | Task ID | Action |
|------|---------|--------|
EOF
}

write_default_next() {
  cat > "$1" <<'EOF'
# Next Task: {TASK_ID} — {Task Name}

**Priority:** P{0/1/2}
**Phase:** {Phase or module}
**Effort:** {Hours}
**Dependencies:** {IDs or "None"}
**Status:** Selected

## Description

{Brief summary pulled from the workplan.}

## Next Step

Run the PLAN command to generate the implementation-ready PRD.
EOF
}

FLOW_VERSION="$(detect_version)"

copy_specs_dir_required() {
  local dir_name="$1"

  if [ ! -d "$SCRIPT_DIR/SPECS/$dir_name" ]; then
    echo "ERROR: required Flow directory is missing: SPECS/$dir_name" >&2
    exit 1
  fi

  mkdir -p "$TARGET/SPECS/$dir_name"
  cp -r "$SCRIPT_DIR/SPECS/$dir_name/." "$TARGET/SPECS/$dir_name/"
  echo "✓ SPECS/$dir_name/ updated"
}

copy_managed_path_required() {
  local rel_path="$1"
  local src_path="$SCRIPT_DIR/$rel_path"
  local dst_path="$TARGET/$rel_path"

  if [ ! -e "$src_path" ]; then
    echo "ERROR: required Flow path is missing: $rel_path" >&2
    exit 1
  fi

  mkdir -p "$(dirname "$dst_path")"
  rm -rf "$dst_path"
  cp -R "$src_path" "$dst_path"
  echo "✓ $rel_path updated"
}

echo "Installing Flow into: $TARGET"
echo ""

# --- SPECS folders managed by Flow (always updated) ---
mkdir -p "$TARGET/SPECS"
copy_specs_dir_required "COMMANDS"
copy_specs_dir_required "ROLES"
if [ -f "$SCRIPT_DIR/SPECS/VERSION" ]; then
  cp "$SCRIPT_DIR/SPECS/VERSION" "$TARGET/SPECS/VERSION"
else
  printf "%s\n" "$FLOW_VERSION" > "$TARGET/SPECS/VERSION"
fi
echo "✓ SPECS/VERSION updated ($FLOW_VERSION)"

# --- Flow-managed Codex assets (always updated) ---
copy_managed_path_required ".agents/skills/flow-run"
copy_managed_path_required ".agents/skills/flow-setup"
copy_managed_path_required ".agents/skills/flow-update"
copy_managed_path_required "plugins/flow"

if [ ! -f "$SCRIPT_DIR/.agents/plugins/marketplace.json" ]; then
  echo "ERROR: required Flow file is missing: .agents/plugins/marketplace.json" >&2
  exit 1
fi
if [ ! -f "$TARGET/.agents/plugins/marketplace.json" ]; then
  mkdir -p "$TARGET/.agents/plugins"
  cp "$SCRIPT_DIR/.agents/plugins/marketplace.json" "$TARGET/.agents/plugins/marketplace.json"
  echo "✓ .agents/plugins/marketplace.json created"
else
  echo "  .agents/plugins/marketplace.json already exists — skipped"
fi

# --- User files (only created if missing) ---

if [ ! -f "$TARGET/SPECS/Workplan.md" ]; then
  if [ -f "$SCRIPT_DIR/templates/Workplan_Example.md" ]; then
    cp "$SCRIPT_DIR/templates/Workplan_Example.md" "$TARGET/SPECS/Workplan.md"
  else
    write_default_workplan "$TARGET/SPECS/Workplan.md"
  fi
  echo "✓ SPECS/Workplan.md created"
else
  echo "  SPECS/Workplan.md already exists — skipped"
fi

if [ ! -f "$TARGET/SPECS/ARCHIVE/INDEX.md" ]; then
  mkdir -p "$TARGET/SPECS/ARCHIVE/_Historical"
  if [ -f "$SCRIPT_DIR/templates/Archive_Index_Example.md" ]; then
    cp "$SCRIPT_DIR/templates/Archive_Index_Example.md" "$TARGET/SPECS/ARCHIVE/INDEX.md"
  else
    write_default_archive_index "$TARGET/SPECS/ARCHIVE/INDEX.md"
  fi
  echo "✓ SPECS/ARCHIVE/INDEX.md created"
else
  echo "  SPECS/ARCHIVE/INDEX.md already exists — skipped"
fi

if [ ! -f "$TARGET/SPECS/INPROGRESS/next.md" ]; then
  mkdir -p "$TARGET/SPECS/INPROGRESS"
  if [ -f "$SCRIPT_DIR/templates/next_example.md" ]; then
    cp "$SCRIPT_DIR/templates/next_example.md" "$TARGET/SPECS/INPROGRESS/next.md"
  else
    write_default_next "$TARGET/SPECS/INPROGRESS/next.md"
  fi
  echo "✓ SPECS/INPROGRESS/next.md created"
else
  echo "  SPECS/INPROGRESS/next.md already exists — skipped"
fi

if [ ! -d "$TARGET/.flow" ]; then
  mkdir -p "$TARGET/.flow"
  echo "✓ .flow/ created"
else
  echo "  .flow/ already exists — skipped"
fi

echo ""
echo "Done. Next: fill in .flow/params.yaml — see SPECS/COMMANDS/SETUP.md"
