#!/usr/bin/env bash
set -euo pipefail

# Flow installer
# Usage:
#   ./install.sh              — install into current directory
#   ./install.sh /path/repo   — install into target directory

TARGET="${1:-.}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

detect_version() {
  if [ -f "$SCRIPT_DIR/SPECS/VERSION" ]; then
    tr -d '[:space:]' < "$SCRIPT_DIR/SPECS/VERSION"
    return
  fi

  if [ -f "$SCRIPT_DIR/SPECS/COMMANDS/FLOW.md" ]; then
    awk '/^\*\*Version:\*\*/ {print $2; exit}' "$SCRIPT_DIR/SPECS/COMMANDS/FLOW.md"
    return
  fi

  echo "0.0.0"
}

write_default_workplan() {
  cat > "$1" <<'EOF'
# Project Workplan

Replace this file with your own tasks. Generated by install.sh fallback template.
EOF
}

write_default_archive_index() {
  cat > "$1" <<'EOF'
# Tasks Archive

**Last Updated:** YYYY-MM-DD

## Archived Tasks

| Task ID | Folder | Archived | Verdict |
|---------|--------|----------|---------|

## Historical Artifacts

| Folder | Description |
|--------|-------------|
| [_Historical/](_Historical/) | Non-task artifacts |

## Archive Log

| Date | Task ID | Action |
|------|---------|--------|
EOF
}

write_default_next() {
  cat > "$1" <<'EOF'
# Next Task: {TASK_ID} — {Task Name}

**Priority:** P{0/1/2}
**Phase:** {Phase or module}
**Effort:** {Hours}
**Dependencies:** {IDs or "None"}
**Status:** Selected

## Description

{Brief summary pulled from the workplan.}

## Next Step

Run the PLAN command to generate the implementation-ready PRD.
EOF
}

FLOW_VERSION="$(detect_version)"

echo "Installing Flow into: $TARGET"
echo ""

# --- COMMANDS and VERSION (always updated) ---
mkdir -p "$TARGET/SPECS"
mkdir -p "$TARGET/SPECS/COMMANDS"
cp -r "$SCRIPT_DIR/SPECS/COMMANDS/." "$TARGET/SPECS/COMMANDS/"
if [ -f "$SCRIPT_DIR/SPECS/VERSION" ]; then
  cp "$SCRIPT_DIR/SPECS/VERSION" "$TARGET/SPECS/VERSION"
else
  printf "%s\n" "$FLOW_VERSION" > "$TARGET/SPECS/VERSION"
fi
echo "✓ SPECS/COMMANDS/ updated ($FLOW_VERSION)"

# --- User files (only created if missing) ---

if [ ! -f "$TARGET/SPECS/Workplan.md" ]; then
  if [ -f "$SCRIPT_DIR/templates/Workplan_Example.md" ]; then
    cp "$SCRIPT_DIR/templates/Workplan_Example.md" "$TARGET/SPECS/Workplan.md"
  else
    write_default_workplan "$TARGET/SPECS/Workplan.md"
  fi
  echo "✓ SPECS/Workplan.md created"
else
  echo "  SPECS/Workplan.md already exists — skipped"
fi

if [ ! -f "$TARGET/SPECS/ARCHIVE/INDEX.md" ]; then
  mkdir -p "$TARGET/SPECS/ARCHIVE/_Historical"
  if [ -f "$SCRIPT_DIR/templates/Archive_Index_Example.md" ]; then
    cp "$SCRIPT_DIR/templates/Archive_Index_Example.md" "$TARGET/SPECS/ARCHIVE/INDEX.md"
  else
    write_default_archive_index "$TARGET/SPECS/ARCHIVE/INDEX.md"
  fi
  echo "✓ SPECS/ARCHIVE/INDEX.md created"
else
  echo "  SPECS/ARCHIVE/INDEX.md already exists — skipped"
fi

if [ ! -f "$TARGET/SPECS/INPROGRESS/next.md" ]; then
  mkdir -p "$TARGET/SPECS/INPROGRESS"
  if [ -f "$SCRIPT_DIR/templates/next_example.md" ]; then
    cp "$SCRIPT_DIR/templates/next_example.md" "$TARGET/SPECS/INPROGRESS/next.md"
  else
    write_default_next "$TARGET/SPECS/INPROGRESS/next.md"
  fi
  echo "✓ SPECS/INPROGRESS/next.md created"
else
  echo "  SPECS/INPROGRESS/next.md already exists — skipped"
fi

if [ ! -d "$TARGET/.flow" ]; then
  mkdir -p "$TARGET/.flow"
  echo "✓ .flow/ created"
else
  echo "  .flow/ already exists — skipped"
fi

echo ""
echo "Done. Next: fill in .flow/params.yaml — see SPECS/COMMANDS/SETUP.md"
