# .flow/params.yaml
# Project-specific config for Flow self-development.

project:
  name: Flow
  description: Documentation-driven workflow framework implemented as Markdown specs and shell tooling
  language: Markdown/Bash
  package_manager: make
  default_branch: main

verify:
  tests: make test
  lint: make lint

task_system:
  kind: file                # file | github | jira | linear | none
  project_key: Flow         # optional lightweight scope key
  task_url_template: "SPECS/Workplan.md#p1-t1-add-task_system-section-to-flow-paramsyaml"  # optional markdown anchor template
